spring:
  profiles:
    active: dev
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
    autoMappingUnknownColumnBehavior: WARNING
  global-config:
    db-config:
      logic-delete-value: 1 #逻辑删除  配合@TableLogic
      logic-not-delete-value: 0 #逻辑不删除
      insert-strategy: ignored  # 插入时字段直接插入，不进行任何判断（建议数据库表每个字段设置默认值）
      update-strategy: not_null # 更新时字段如果为null，就不进行更新该字段。
