spring:
  profiles:
    active: dev
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
    autoMappingUnknownColumnBehavior: WARNING
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 打印sql语句和入参
  global-config:
    db-config:
      logic-delete-value: 1 #逻辑删除  配合@TableLogic
      logic-not-delete-value: 0 #逻辑不删除
      update-strategy: not_null # 更新时字段如果为null，就不进行更新该字段。
      insert-strategy: not_null # 插入时如果字段为null,就不插入数据，建议数据库表字段设置默认值
