spring:
  profiles:
    active: dev
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml  #xml所在位置  不设置默认是在mapper类同级
  configuration:
    mapUnderscoreToCamelCase: true  # 开启驼峰匹配  默认为true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 打印sql语句和入参数据
  global-config:
    db-config:
      logic-delete-value: 1 #逻辑删除  配合@TableLogic注解
      logic-not-delete-value: 0 #逻辑不删除
      update-strategy: not_null # 更新时字段如果为null，就不进行更新该字段。
      insert-strategy: not_null # 插入时如果字段为null,就不插入数据，建议数据库表字段设置默认值
