spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      username: admin
      password: root1234
      url: jdbc:mysql://127.0.0.1:3306/springboot?autoReconnect=true&autoReconnectForPools=true&useUnicode=true&characterEncoding=utf8&useSSL=false
      # 连接池的配置信息
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j,config
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      web-stat-filter:
        enabled: true
        url-pattern: "/"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
  # WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
#  spring.datasource.druid.web-stat-filter.enabled= #是否启用StatFilter默认值false
#  spring.datasource.druid.web-stat-filter.url-pattern=
#  spring.datasource.druid.web-stat-filter.exclusions=
#  spring.datasource.druid.web-stat-filter.session-stat-enable=
#  spring.datasource.druid.web-stat-filter.session-stat-max-count=
#  spring.datasource.druid.web-stat-filter.principal-session-name=
#  spring.datasource.druid.web-stat-filter.principal-cookie-name=
#  spring.datasource.druid.web-stat-filter.profile-enable=
      stat-view-servlet:
        enabled: true
        url-pattern: "/druid/*"
        login-username: admin
        login-password: 123456
        reset-enable: false
        allow: ""  # 白名单 表示所有
        deny: 192.168.1.12 # 黑名单

#  # StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
#  spring.datasource.druid.stat-view-servlet.enabled= #是否启用StatViewServlet（监控页面）默认值为false（考虑到安全问题默认并未启动，如需启用建议设置密码或白名单以保障安全）
#  spring.datasource.druid.stat-view-servlet.url-pattern=
#  spring.datasource.druid.stat-view-servlet.reset-enable=
#  spring.datasource.druid.stat-view-servlet.login-username=
#  spring.datasource.druid.stat-view-servlet.login-password=
#  spring.datasource.druid.stat-view-servlet.allow=
#  spring.datasource.druid.stat-view-servlet.deny=
